# Default values for kbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: ghcr.io/dapr
  repository: ashcherbatyi
  tag: v1.0.3-31531fc
  arch: amd64
  os: linux
teleToken: ""
secret:
  name: "tele-token-secret"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
